### ISSUE TITLE
core::Tensor转tf Tensor

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#104]
请问如何能把core::Tensor转换成tf的tensor

**Comment by feifeibear** [comment]
没有用过tensorflow->dlpack转换，但我从网上查找了一些资料，希望对你有用
tensorflow 2.0有一些实验性质的接口
https://www.tensorflow.org/api_docs/python/tf/experimental/dlpack/from_dlpack
也有第三方repo
https://github.com/VoVAllen/tf-dlpack
