### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#109]
请问大佬 运行 bash tools/compile.sh $PWD -DWITH_GPU=ON /tmp/build报错：
avx512fintrin.h(1761): error: identifier "__builtin_ia32_sqrtsd_round" is undefined 是啥原因啊？

**Comment by feifeibear** [comment]
docker里运行的么？

**Comment by hadoop2xu** [comment]
gcc和g++版本过高导致的，已解决
