### ISSUE TITLE
When will albert be released ?

### ISSUE THREAD

**Issue by xutianming** [Tencent/TurboTransformers#110]
Dear developers, I am working on optimizing albert serving performance. 
I find that albert is under development. When will it be released ?

**Comment by feifeibear** [comment]
see branch feature/albert. We now have Albert layer implementation and I am working on it this week. 
If possible, could you provide some code snippets showing how you use Albert (which pretrained model, in what task)? It will be helpful for us to provide APIs more specifically.

**Comment by xutianming** [comment]
Currently, I get a TensorFlow saved model optimized by tensorrt and serve with Tensorflow Serving. 
The model is modified from [modeling_tf_albert](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_tf_albert.py) for online token classification. 
My preferred input and output is TensorFlow saved model so it will be compatible with out current serving infrastructure.

**Comment by feifeibear** [comment]
Fine, tf-serving forces everyone to store their model in tensorflow format. 
Actually, PyTorch serving is not much harder. It's time to put our serving framework open-sourced on schedule.

**Comment by xutianming** [comment]
According to [ISSUE#13](https://github.com/Tencent/TurboTransformers/issues/13), Tensorflow Saved Model format is also supported as input. Will it work for albert?

**Comment by feifeibear** [comment]
Yes, a huggingface-based tensorflow model will be supported, but it will be developed after PyTorch version.

**Comment by feifeibear** [comment]
Now, the 2020.07.07 Albert model has already included in the branch develop. You can load an Albert model from a PyTorch model in memory. Loading from pre-trained model on disk or npz model on disk is still not supported. I know it is still far from what you need.
See this file for details. turbo_transformers/python/tests/albert_model_test.py how to load albert model.

![image](https://user-images.githubusercontent.com/5706969/86745321-d9b8f680-c06c-11ea-97e2-ed9bc7810969.png)

**Comment by xutianming** [comment]
That's great. I can develop based on your solution. That already helps a lot.

**Comment by feifeibear** [comment]
I hope this will help
