### ISSUE TITLE
tensor数据类型不匹配

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#112]
运行自定义代码，报错L：
RuntimeError: enforce errordetails::IsDataType<T>(t.dtype) at /TurboTransformers/turbo_transformers/core/tensor.h:302
data type mismatch, request l, actual (0,32)
Callstack 0
请问大佬，可能是什么原因啊？

**Comment by feifeibear** [comment]
传入数据类型不配备，应该long你穿了个float。这个异常信息应该写的很清楚了，(0, 32)表示dlpack类型是0，32 bits。

**Comment by hadoop2xu** [comment]
> 传入数据类型不配备，应该long你穿了个float。这个异常信息应该写的很清楚了，(0, 32)表示dlpack类型是0，32 bits。

嗯嗯 ，多谢

**Comment by feifeibear** [comment]
你在开发什么功能？我看看我们能不能给你一些支持。

**Comment by hadoop2xu** [comment]
我看到Turbo在embedding_lookup对很好的并行性实现，我用tf实现的算法中也包含embedding_lookup操作，所以我想用turbo实现替换tf实现，期待有一定的推理性能提升。

**Comment by feifeibear** [comment]
没必要吧，embedding根本就不是热点。

**Comment by hadoop2xu** [comment]
> 没必要吧，embedding根本就不是热点。
水平有限 😂，能想到的办法不多

**Comment by hadoop2xu** [comment]
> > 没必要吧，embedding根本就不是热点。
> > 水平有限 😂，能想到的办法不多

再请教下loguru::current_verbosity_cutoff() >= 3这个日志开关如何开启 ？

**Comment by feifeibear** [comment]
turbo_transformers.set_stderr_verbose_level(3)

**Comment by hadoop2xu** [comment]
> turbo_transformers.set_stderr_verbose_level(3)

👍， 回复神速

**Comment by hadoop2xu** [comment]
> .set_stderr_verbose_level(3)
