### ISSUE TITLE
cmake crash with "Cannot find librt from"

### ISSUE THREAD

**Issue by yangfly** [Tencent/TurboTransformers#113]
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release .. -DWITH_GPU=OFF
```
-- /include
-- Blas provider is mkl
-- pybind11 v2.4.dev4
-- OpenMP USED FLAGS
CMake Error at CMakeLists.txt:79 (message):
  Cannot find librt from
```
thank you.

**Comment by feifeibear** [comment]
Crash In docker? It seems your own compilation environment's problem.

**Comment by yangfly** [comment]
Yes, it's on my own env. (Centos7, miniconda, python3.7).
I've found /usr/lib64/librt-2.17.so, but no librt.a in $CONDA_PREFIX
Do I miss any dependence or must build in docker?
Thank you.

**Comment by feifeibear** [comment]
列夫托尔斯泰龙曾经说过：“编译正确的环境都是一样的,编译错误环境的环境各有各的错误”。
这也是为什么我们只能保证你在docker里面复现的原因，个人系统环境的库只能靠自己Google了。

**Comment by yangfly** [comment]
I'll try docker, thank you.

**Comment by ztpxy1997** [comment]
I also encountered this problem. Could you solve it?

**Comment by feifeibear** [comment]
目前编译依赖的是conda安装的mkl
1. 检查自己的conda路径是否生效，是不是PATH中能找lib的目录
2. 争取设置mkl在cmake的路径
https://github.com/Tencent/TurboTransformers/blob/master/CMakeLists.txt#L48
