### ISSUE TITLE
The performance compare with Zhihu CuBert

### ISSUE THREAD

**Issue by wugh** [Tencent/TurboTransformers#12]
Hi, 

Zhihu also have a optimized bert project [Cubert](https://github.com/zhihu/cuBERT), have you compare speed with that one?

**Comment by feifeibear** [comment]
> Hi,
> 
> Zhihu also have a optimized bert project [Cubert](https://github.com/zhihu/cuBERT), have you compare speed with that one?

No, we have compared our performance with state-of-the-art solutions.
