### ISSUE TITLE
Slower than original torch model (batch_gemm kernel is slow on my CPU)

### ISSUE THREAD

**Issue by stevewyl** [Tencent/TurboTransformers#127]
Hi, I just run the example in the readme and found the turbo_model is slower than the original torch model. I pull the latest CPU docker image and run the sample script in the container. 
I use the following command to start the container:
```bash
docker run -itd --name turbo_test thufeifeibear/turbo_transformers_cpu:latest
docker exec -it turbo_test bash
```
![image](https://user-images.githubusercontent.com/12755003/87403238-30837a80-c5ef-11ea-9779-041658474ba5.png)

**Comment by feifeibear** [comment]
I assume you run PyTorch and Turbo in the same context. Multiple Threading mechanics may conflict with each other.

**Comment by stevewyl** [comment]
Thanks for your reply! This is the screenshot of running the benchmark.sh, Turbo still got the slowest QPS. The CPU is Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz.
![image](https://user-images.githubusercontent.com/12755003/87410397-d687b280-c5f8-11ea-97d4-56bbe9e55ea2.png)

**Comment by feifeibear** [comment]
Interesting. Maybe your CPU is not friendly with Turbo.

**Comment by stevewyl** [comment]
@feifeibear I change another machine with CPU Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, still got similar results.
![image](https://user-images.githubusercontent.com/12755003/87412860-1bf9af00-c5fc-11ea-95d5-b0c80917a0bf.png)
Please check whether my container command wrong? Thanks!

**Comment by feifeibear** [comment]
I do not think so. Could you please to profile the BERT for more details?
https://github.com/Tencent/TurboTransformers/blob/master/docs/profiler.md

**Comment by stevewyl** [comment]
Following codes is the profile code:
```python
import transformers
import torch
import turbo_transformers

num_threads = 4
turbo_transformers.set_num_threads(num_threads)

model_id = "bert-base-uncased"
model = transformers.BertModel.from_pretrained(model_id)
model.eval()

input_ids = torch.tensor(
    ([12166, 10699, 16752, 4454], [5342, 16471, 817, 16022]),
    dtype=torch.long)
position_ids = torch.tensor(([1, 0, 0, 0], [1, 1, 1, 0]), dtype=torch.long)
segment_ids = torch.tensor(([1, 1, 1, 0], [1, 0, 0, 0]), dtype=torch.long)

tt_model = turbo_transformers.BertModel.from_torch(model)

with turbo_transformers.pref_guard("info") as perf:
    res = tt_model(input_ids, position_ids=position_ids, token_type_ids=segment_ids)
```
 The result:
![image](https://user-images.githubusercontent.com/12755003/87420804-7ef14300-c608-11ea-8fef-bd71081fffae.png)

**Comment by feifeibear** [comment]
Aha, I find the problem. batch_gemm3 shall not take that much of time.
See my profiling results. 
![image](https://user-images.githubusercontent.com/5706969/87493167-cadecf00-c67e-11ea-9d84-1d13b794e388.png)

**Comment by feifeibear** [comment]
If you are using the MKL as blas provider. It will use `cblas_sgemm_batch` to do batch_gemm.
see it here.
https://github.com/Tencent/TurboTransformers/blob/master/turbo_transformers/layers/kernels/mat_mul.cpp#L181
In my humble opinion, the reason may come from the mkl provided by PyTorch not suitable for your CPU.
You can follow these instructions to debug.
1. Modify CMakeLists and use OpenBLAS as blas provider. (May need to install gfortran in your container)
2. Run profiling script again. See if batch_gemm3 return to normal. 
3. If that works, reinstall MKL using conda (Google for the best command), because OpenBLAS is not the best BLAS on Intel CPU.

**Comment by stevewyl** [comment]
I just run the profiling script again. the batch_gemm3 returns to normal. 
![image](https://user-images.githubusercontent.com/12755003/87494923-c2889300-c682-11ea-9c3c-ba91cc1542c2.png)
ok. I will try OpenBLAS later.

**Comment by feifeibear** [comment]
What

**Comment by stevewyl** [comment]
I run the benchmark script again. The same result, Turbo is slower than torch. At this time, only I use 4 CPU cores
![image](https://user-images.githubusercontent.com/12755003/87497549-527d0b80-c688-11ea-9a3a-cf42d9a0e147.png)

**Comment by feifeibear** [comment]
According to your screenshots, Turbo has already done a good job. Most of time is wasted on GEMM, which is the duty of MKL. 
You can set MKL_VERBOSE=1 in your cmd. Obverse routine time diffs between PyTorch and Turbo.

**Comment by feifeibear** [comment]
TODO : CPU-version Turbo uses the same MKL conda packages as PyTorch. We should check (1 ) Whether specific MKL versions make turbo slow? (2) Did we use different env variables to damage MKL performance?

**Comment by feifeibear** [comment]
Hi @stevewyl , I remake a docker image. Update it to dockerhub.
`
docker pull thufeifeibear/turbo_transformers_cpu:latest
`
I found the MKL inside the original docker images will be extremely slow on some CPUs. I reinstall it and it looks better on my own CPU.
