### ISSUE TITLE
MKL is slow in Turbo

### ISSUE THREAD

**Issue by feifeibear** [Tencent/TurboTransformers#143]
I am using the docker images from dockerhub
`thufeifeibear/turbo_transformers_cpu:latest`

I export MKL_VERBOSE=1, and compared SGEMM time in PyTorch and Turbo.
Why MKL is much more fast in PyTorch than Turbo?
`
Pytorch
`
MKL_VERBOSE SGEMM(t,n,768,8,768,0x7ffcdacca284,0x7f8daf95d040,768,0x7f8e328105c0,768,0x7ffcdacca280,0x7f8e32822680,768) **190.00us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM(t,n,768,8,768,0x7ffcdacca284,0x7f8daf71c040,768,0x7f8e328105c0,768,0x7ffcdacca280,0x7f8e328286c0,768) **149.12us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM_BATCH(N,N,0x7ffcdacca2fc,0x7ffcdacca300,0x7ffcdacca2f8,0x7ffcdacca2f4,0x7f8e326929c0,0x7ffcdacca2ec,0x7f8e30ba3580,0x7ffcdacca2f0,0x7ffcdacca2e8,0x7f8e325da670,0x7ffcdacca2e4,0x7ffcdacca1a8,0x7 **22.83us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM_BATCH(N,N,0x7ffcdacca2fc,0x7ffcdacca300,0x7ffcdacca2f8,0x7ffcdacca2f4,0x7f8e326929c0,0x7ffcdacca2ec,0x7f8e30ba3580,0x7ffcdacca2f0,0x7ffcdacca2e8,0x7f8e325da670,0x7ffcdacca2e4,0x7ffcdacca1a8,0x7 **14.40us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM(t,n,768,8,768,0x7ffcdacca374,0x7f8daf4db040,768,0x7f8e328407c0,768,0x7ffcdacca370,0x7f8e32816600,768) **93.84us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM(t,n,3072,8,768,0x7ffcdaccaaa4,0x7f8daebda040,768,0x7f8e328286c0,768,0x7ffcdaccaaa0,0x7f8e3283a780,3072) **438.84us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM(t,n,768,8,3072,0x7ffcdaccaaa4,0x7f8dae2d9040,3072,0x7f8e328527c0,3072,0x7ffcdaccaaa0,0x7f8e3282e700,768) **501.67us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8
MKL_VERBOSE SGEMM(t,n,768,2,768,0x7ffcdaccb734,0x7f8dae098040,768,0x7f8e3283a780,3072,0x7ffcdaccb730,0x7f8e3279f340,768) **78.68us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:8

`
Turbo
`
MKL_VERBOSE SGEMM_BATCH(T,N,0x7ffcdacca118,0x7ffcdacca11c,0x7ffcdacca114,0x7ffcdacca094,0x7f8e326a70a0,0x7ffcdacca0d8,0x7f8e3267fd50,0x7ffcdacca0dc,0x7ffcdacca090,0x7f8e326a7170,0x7ffcdacca0d4,0x7ffcdacc9fe8,0x7ffcdacca124) **14.74us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:4
MKL_VERBOSE SGEMM_BATCH(N,N,0x7ffcdacca118,0x7ffcdacca11c,0x7ffcdacca114,0x7ffcdacca094,0x7f8e326a70a0,0x7ffcdacca0d8,0x7f8e3267fd50,0x7ffcdacca0dc,0x7ffcdacca090,0x7f8e326a7170,0x7ffcdacca0d4,0x7ffcdacc9fe8,0x7ffcdacca124) **35.14us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:4
MKL_VERBOSE SGEMM(N,N,768,8,768,0x7ffcdacca308,0x7f8e44a81100,768,0x7f8e3e0d8f40,768,0x7ffcdacca310,0x7f8e3e1ab300,768) **169.02us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:4
MKL_VERBOSE SGEMM(N,N,3072,8,768,0x7ffcdaccbca8,0x7f8e4bb013c0,3072,0x7f8e3e1ab300,768,0x7ffcdaccbcb0,0x7f8e3e17b240,3072) **620.16us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:4
MKL_VERBOSE SGEMM(N,N,768,8,3072,0x7ffcdaccbbc8,0x7f8e4cd01440,768,0x7f8e3e17b240,3072,0x7ffcdaccbbd0,0x7f8e3e11b040,768) **566.76us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:4
MKL_VERBOSE SGEMM(N,N,768,2,768,0x7ffcdaccc7a8,0x7f8e4c401400,768,0x7f8e3279f340,768,0x7ffcdaccc7b0,0x7f8e327e6c00,768) **160.20us** CNR:OFF Dyn:1 FastMM:1 TID:0  NThr:4

**Comment by yao-matrix** [comment]
有没可能PyTorch使用的线程比Turbo使用的线程多? 看到log里PyTorch NThr是8， 而TurboTransformer是4.

**Comment by feifeibear** [comment]
应该不是，控制变量来观察，用pytorch 1.1.0版本就会被1.5.0版本快两倍。

**Comment by feifeibear** [comment]
If you want to use turbo as the backend instead of onnxrt. Directly linking an MKL of Pytorch installed by conda will lead to poor performance in our hand-crafted C++ version. You should install an official MKL and set MKL PATH in CMakeLists.txt. As a not so elegant alternative, you can uninstall OpenNMT-py and downgrade torch to 1.1.0.
