### ISSUE TITLE
Running the CPU docker container throws an error

### ISSUE THREAD

**Issue by tenshis** [Tencent/TurboTransformers#163]
Trying to run your docker container for CPU throws the following error:

`/bin/bash: /opt/conda/lib/libtinfo.so.6: no version information available (required by /bin/bash)`

**Comment by feifeibear** [comment]
Yes, it doesn't matter. The container works well anyway.

**Comment by tenshis** [comment]
I'm super confused. It's not starting up... I can't access the container from the shell. Why does it not matter?

**Comment by feifeibear** [comment]
I never fail to start a container on my machines.
Did you try to build a docker image by yourself?
