### ISSUE TITLE
module turbo_transformer has no attribute 'GPT2Model'

### ISSUE THREAD

**Issue by 652994331** [Tencent/TurboTransformers#167]
Hi, i am using the GPT-2 Test at this path: /TurboTranbsformer/example/python/gpt2_example.py. The image i am using is  thufeifeibear/turbo_transformers:0.2.0-cuda10.0-cudnn7-devel-ubuntu18.04-gpu-release. Could you please help me, thanks.

**Comment by feifeibear** [comment]
Please use the latest docker image.

**Comment by 652994331** [comment]
@feifeibear thanks for your reply. I am using the latest GPu version docker image now. i am using the "--gpus all " to use cuda. But it seems when i was using the gpt2_example.py under /TurboTransformer/examples/python/. i got an error message like this:
 
![image](https://user-images.githubusercontent.com/51428350/91924094-b97d7080-ec86-11ea-9af3-a8bd3cd238cc.png). a little bit  connfused now

**Comment by feifeibear** [comment]
The GPU container can run GPT2 on GPU devices only. Try to run it on the CPU will fail.
You should remove the cpu logic in the code.
