### ISSUE TITLE
try to install tensorflow in the lastest gpu docker:no space

### ISSUE THREAD

**Issue by 652994331** [Tencent/TurboTransformers#172]
Hi, i was trying to install tensorflow-gpu==1.13.1 in the latest gpu docker provided by u. However, "could not install , no space left on the device". Could you please hele me with this, thanks

**Comment by feifeibear** [comment]
Your computer has no space left. You may need to delete some useless files or use a computer with more extra disk space.

**Comment by feifeibear** [comment]
I close this issue because the error is not related to the function of TurboTransformers.
