### ISSUE TITLE
 Serving Framework 

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#177]
paper中介绍了 Serving Framework ，这部分代码是没有开源吗？

**Comment by feifeibear** [comment]
不同业务中会采用不同Serving框架，没有开源的必要性，论文里采用Python Asio实现，工作量很小。

**Comment by hadoop2xu** [comment]
> 不同业务中会采用不同Serving框架，没有开源的必要性，论文里采用Python Asio实现，工作量很小。

明白了
