### ISSUE TITLE
How  to test  ' spent on GEMM kernels '  ? what tool used ?

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#178]
![image](https://user-images.githubusercontent.com/48076281/96557194-7e91d380-12ec-11eb-8726-62bff4050dde.png)
 请问下大佬 这个占比是用什么工具分析出来的 ？

**Comment by feifeibear** [comment]
nvvp工具看time line得到

**Comment by feifeibear** [comment]
代码里也有手工计时函数，可以打印一些丑陋的日志。
