### ISSUE TITLE
安装环境

### ISSUE THREAD

**Issue by Cumberbatch08** [Tencent/TurboTransformers#18]
小白说一下，感觉好用是很好用；但是这个安装流程是不是太重型了。。。

**Comment by feifeibear** [comment]
感谢支持！docker的方式确实比较繁琐，主要是为了使用者二次开发考虑，大家可以轻易更改源代码定制自己的需求。
@reyoung re @chengduoZH 我们可以考虑将Conda包上传到Anaconda云

**Comment by Cumberbatch08** [comment]
@feifeibear   从我个人来看，还没get到二次开发的迫切性，我希望能够通过你们的方案对bert 的推理速度做到加速，所以暴露标准的接口满足这样的需求，已经解决很多人需求了。

**Comment by feifeibear** [comment]
> @feifeibear 从我个人来看，还没get到二次开发的迫切性，我希望能够通过你们的方案对bert 的推理速度做到加速，所以暴露标准的接口满足这样的需求，已经解决很多人需求了。

了解了解

**Comment by reyoung** [comment]
使用 #19 这个issue来跟踪conda 安装包的开发进度。
