### ISSUE TITLE
cuda 11的支持

### ISSUE THREAD

**Issue by bigprince97** [Tencent/TurboTransformers#216]
感谢作者的开源工作，请问一下,turbo transformers支持cuda11吗？我可以正常在2080ti上使用turbo transformer的gpu版本，但是在3090上没法使用，运行会卡很久，3090的cuda版本是11。

**Comment by feifeibear** [comment]
RTX 2060支持cuda11没问题，换一个gpu之后重新编译了吧？

**Comment by bigprince97** [comment]
没有重新编译，直接在3090上拉取的turbo transformer的gpu镜像使用的

**Comment by feifeibear** [comment]
那你肯定得重新编译呀，硬件架构都不一样，编出来的库肯定没法直接移植。

**Comment by bigprince97** [comment]
嗯嗯，我试试，感谢！
