### ISSUE TITLE
Turbo installation problem with MKL

### ISSUE THREAD

**Issue by QSZL-SZ** [Tencent/TurboTransformers#234]
I tried to install the GPU version of turbotransformer but my installation stuck on 
`sh tools/build_docker_gpu.sh $PWD` since CMake cannot find MKL. 
This problem may due to my MKL is installed via intel oneapi so I changed MKLROOT in CMAKELIST.txt:48 to /opt/intel/oneapi/mkl/latest and this method partly solved this problem. CMake now can find MKL_INFERFACE/THREADS/CORE_LIBRARY but still said missing MKL_LIBRARIES. 
I guess the reason is that in FINDmkl.cmake:82, MKL_LIBRARIES needs IOMP_LIBRARY. IOMP_LIBRARY needs to find iomp5 (FINDmkl.cmake:74) which does not exist in MKL in oneapi now.
Can you give some hints to solve this problem? Thanks for the help!

**Comment by feifeibear** [comment]
If you use GPU version. You can install mkl through conda. conda install mkl?

**Comment by QSZL-SZ** [comment]
You mean I should reinstall MKL through conda?
Thanks. I'll have a try.

**Comment by QSZL-SZ** [comment]
Thanks for the help. Finally, it is built successfully. However, 19 out of 31 of the unit tests are failed and their errors are all like the one in the attached snapshot. (symbol lookup error: /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_thread.so: undefined symbol: __kmpc_global_thread_num)
Could you give me some hints? Thanks!
![ERROR](https://user-images.githubusercontent.com/83391440/116666957-36213580-a961-11eb-8d9f-55a0c58d22c8.PNG)

**Comment by feifeibear** [comment]
Maybe you should unset all your own MKL environments.

**Comment by QSZL-SZ** [comment]
I downloaded the pre-built docker image of the CPU version and passed the unit test. Nonetheless when I tried to run the benchmark in docker by running `root@1fabd7ac3b36:/workspace/benchmark# bash run_cpu_fixed_benchmark.sh` it returned a runtime error.
I had used `pip uninstall onnxruntime-gpu` and `pip install onnxruntime` before running the benchmark.
Here is the terminal message after running the benchmark.

root@1fabd7ac3b36:/workspace/benchmark# bash run_cpu_fixed_benchmark.sh
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2021-05-01 05:28:43.574 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2021-05-01 05:28:43.574 (   0.001s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /workspace/benchmark
2021-05-01 05:28:43.575 (   0.001s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2021-05-01 05:28:43.575 (   0.002s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
{"QPS": 0.905516247470458, "elapsed": 165.65136232400255, "n": 150, "batch_size": 1, "seq_len": 40, "framework": "turbo", "thread_num": 4, "model_name": "albert"}
2021-05-01 05:31:31.791 ( 168.218s) [main thread     ]             loguru.cpp:489   INFO| atexit
{"QPS": 2.8254704364522873, "elapsed": 53.088504507002654, "n": 150, "batch_size": 1, "seq_len": 40, "framework": "torch", "thread_num": 4, "model_name": "albert"}
/opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_albert.py:229: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  position_ids = self.position_ids[:, :seq_length]
/opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_utils.py:1669: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  input_tensor.shape == tensor_shape for input_tensor in input_tensors
{"QPS": 0.1472345156348595, "elapsed": 1018.7828536890011, "n": 150, "batch_size": 1, "seq_len": 40, "framework": "torch_jit", "n_threads": 4, "model_name": "albert"}
/opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_albert.py:229: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  position_ids = self.position_ids[:, :seq_length]
/opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_utils.py:1669: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  input_tensor.shape == tensor_shape for input_tensor in input_tensors
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/workspace/benchmark/onnx_benchmark_helper.py", line 67, in generate_onnx_model
    torch.onnx.export(model=model, args=(input_ids, ), f=outf)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 351, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 154, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 199, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 740, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 129, in wrapper
    return fn(g, *args)
  File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 1452, in slice
    raise RuntimeError('Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice '
RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "benchmark.py", line 73, in <module>
    main()
  File "benchmark.py", line 67, in main
    onnxruntime_benchmark_creator('CPU')(**kwargs)
  File "/workspace/benchmark/onnx_benchmark_helper.py", line 110, in _impl_
    enable_random))
  File "/opt/miniconda3/lib/python3.7/multiprocessing/pool.py", line 261, in apply
    return self.apply_async(func, args, kwds).get()
  File "/opt/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.

Do you have some idea of the problem here? Thanks for the help.

**Comment by feifeibear** [comment]
> I downloaded the pre-built docker image of the CPU version and passed the unit test. Nonetheless when I tried to run the benchmark in docker by running `root@1fabd7ac3b36:/workspace/benchmark# bash run_cpu_fixed_benchmark.sh` it returned a runtime error.
> I had used `pip uninstall onnxruntime-gpu` and `pip install onnxruntime` before running the benchmark.
> Here is the terminal message after running the benchmark.
> 
> root@1fabd7ac3b36:/workspace/benchmark# bash run_cpu_fixed_benchmark.sh
> date time ( uptime ) [ thread name/id ] file:line v|
> 2021-05-01 05:28:43.574 ( 0.000s) [main thread ] loguru.cpp:610 INFO| arguments: turbo_transformers_cxx
> 2021-05-01 05:28:43.574 ( 0.001s) [main thread ] loguru.cpp:613 INFO| Current dir: /workspace/benchmark
> 2021-05-01 05:28:43.575 ( 0.001s) [main thread ] loguru.cpp:615 INFO| stderr verbosity: 0
> 2021-05-01 05:28:43.575 ( 0.002s) [main thread ] loguru.cpp:616 INFO| -----------------------------------
> {"QPS": 0.905516247470458, "elapsed": 165.65136232400255, "n": 150, "batch_size": 1, "seq_len": 40, "framework": "turbo", "thread_num": 4, "model_name": "albert"}
> 2021-05-01 05:31:31.791 ( 168.218s) [main thread ] loguru.cpp:489 INFO| atexit
> {"QPS": 2.8254704364522873, "elapsed": 53.088504507002654, "n": 150, "batch_size": 1, "seq_len": 40, "framework": "torch", "thread_num": 4, "model_name": "albert"}
> /opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_albert.py:229: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> position_ids = self.position_ids[:, :seq_length]
> /opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_utils.py:1669: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> input_tensor.shape == tensor_shape for input_tensor in input_tensors
> {"QPS": 0.1472345156348595, "elapsed": 1018.7828536890011, "n": 150, "batch_size": 1, "seq_len": 40, "framework": "torch_jit", "n_threads": 4, "model_name": "albert"}
> /opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_albert.py:229: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> position_ids = self.position_ids[:, :seq_length]
> /opt/miniconda3/lib/python3.7/site-packages/transformers/modeling_utils.py:1669: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
> input_tensor.shape == tensor_shape for input_tensor in input_tensors
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "/opt/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "/workspace/benchmark/onnx_benchmark_helper.py", line 67, in generate_onnx_model
> torch.onnx.export(model=model, args=(input_ids, ), f=outf)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/**init**.py", line 168, in export
> custom_opsets, enable_onnx_checker, use_external_data_format)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
> use_external_data_format=use_external_data_format)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
> fixed_batch_size=fixed_batch_size)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 351, in _model_to_graph
> fixed_batch_size=fixed_batch_size, params_dict=params_dict)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 154, in _optimize_graph
> graph = torch._C._jit_pass_onnx(graph, operator_export_type)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/**init**.py", line 199, in _run_symbolic_function
> return utils._run_symbolic_function(*args, **kwargs)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 740, in _run_symbolic_function
> return op_fn(g, *inputs, **attrs)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 129, in wrapper
> return fn(g, *args)
> File "/opt/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py", line 1452, in slice
> raise RuntimeError('Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice '
> RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "benchmark.py", line 73, in
> main()
> File "benchmark.py", line 67, in main
> onnxruntime_benchmark_creator('CPU')(**kwargs)
> File "/workspace/benchmark/onnx_benchmark_helper.py", line 110, in _impl_
> enable_random))
> File "/opt/miniconda3/lib/python3.7/multiprocessing/pool.py", line 261, in apply
> return self.apply_async(func, args, kwds).get()
> File "/opt/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
> raise self._value
> RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.
> 
> Do you have some idea of the problem here? Thanks for the help.

It seems your onnxruntime version is too low? install an onnxruntime higher than 1.4.0
