### ISSUE TITLE
期待支持albert的加速

### ISSUE THREAD

**Issue by lishuaijuly** [Tencent/TurboTransformers#24]

**Comment by feifeibear** [comment]
Sure, albert will be our first priority **after** we finish an attention decoder.

**Comment by yangtianyu92** [comment]
我也觉着。albert 能300 * 12 .8，这框架再把速度 * 2~3，几张T4就能把老板的奇思妙想送上生产了。

**Comment by lsy641** [comment]
> 我也觉着。albert 能300 * 12 .8，这框架再把速度 * 2~3，几张T4就能把老板的奇思妙想送上生产了。

请教下，albert本身似乎只对训练端有加速，推理在large一下模型比bert还慢，您说的300*12.8是什么呀。

**Comment by yangtianyu92** [comment]
哎，是我今天看错了，郁闷。




在2020年05月26日 00:30，lsy641 写道：

我也觉着。albert 能300 * 12 .8，这框架再把速度 * 2~3，几张T4就能把老板的奇思妙想送上生产了。

请教下，albert本身似乎只对训练端有加速，推理在large一下模型比bert还慢，您说的300*12.8是什么呀。

**Comment by feifeibear** [comment]
albert会比bert模型小，但是计算并没有减少吧，如果显存比较紧张的话，线上有可能用albert。

**Comment by yangtianyu92** [comment]
> albert会比bert模型小，但是计算并没有减少吧，如果显存比较紧张的话，线上有可能用albert。
是的。我昨天详细了解后才知道是共享权重计算。我一直以为降低参数量就能提升运行速度。感觉不妙啊。。。
