### ISSUE TITLE
bert_for_sequence_classification_example.py后端使用turbo报错

### ISSUE THREAD

**Issue by Hap-Zhang** [Tencent/TurboTransformers#244]
Hi,@feifeibear

我这边在用bert_for_sequence_classification_example.py这个示例在验证turbo的性能，这个例子貌似默认backend使用的是onnx，我改为turbo之后会报错，请问是需要修改modeling_bert.py这里的代码吗，希望您可以指导一下，谢谢啦。

![image](https://user-images.githubusercontent.com/32810063/128706664-6154a809-c6ee-4e96-9839-034e8b317106.png)

**Comment by feifeibear** [comment]
下载最近的代码或拉取最新镜像，报错和最新的master分支对不上
https://github.com/Tencent/TurboTransformers/blob/master/turbo_transformers/python/turbo_transformers/layers/modeling_bert.py#L508

**Comment by Hap-Zhang** [comment]
您好，其实我现在的环境是在你之前给的最新镜像（FROM thufeifeibear/turbo_transformers_cpu:latest）基础上拉取了github最新代码，然后重新build得到的，报错和代码里面行数不一致，是因为我加了print语句来调试，代码都是最新的

**Comment by Hap-Zhang** [comment]
不好意思，这边是我修改代码引出来的问题，打扰了，可以关闭该issue
