### ISSUE TITLE
支持大模型的推理吗

### ISSUE THREAD

**Issue by 520jefferson** [Tencent/TurboTransformers#253]
目前支持大模型吗？比如30亿（enc dec 均36层) 或者上百亿的，transformer模型，有一些推理优化的性能指标吗？

**Comment by feifeibear** [comment]
大模型推理可以去看一下NVIDIA的FasterTransformer。turbo支持也不难，如果你愿意做一些测试的话，我近半年没有计划去做这件事了。

**Comment by datalee** [comment]
hehe

**Comment by feifeibear** [comment]
> hehe

友商别黑，现在已经很多做Decoder-only LLM的inference了，其实挑战和encoder有比较大的差别了。这issue post的两年前的大模型还不是指decoder-only的。

**Comment by datalee** [comment]
> > hehe
> 
> 友商别黑，现在已经很多做Decoder-only LLM的inference了，其实挑战和encoder有比较大的差别了。这issue post的两年前的大模型还不是指decoder-only的。

好吧
