### ISSUE TITLE
unitest失败

### ISSUE THREAD

**Issue by ArtyZe** [Tencent/TurboTransformers#255]
首先感谢开源如此优秀的代码，
目前安装了cpu版本，在进行单元测试时，在第31个报错，如下：
![image](https://user-images.githubusercontent.com/32027268/148894731-d357afc4-53f6-41e5-87fc-1f165a8c981b.png)
![image](https://user-images.githubusercontent.com/32027268/148894775-4af44846-eb5c-4c3b-a7d7-c5f816054a56.png)
麻烦帮忙看下

**Comment by feifeibear** [comment]
你改小一下diff的tolerance试试，有的处理器的数值精度可能不同。

**Comment by ArtyZe** [comment]
> 你改小一下diff的tolerance试试，有的处理器的数值精度可能不同。

好的，感谢，然后麻烦问下后续有支持nn.MultiheadAttention模块的计划吗

**Comment by feifeibear** [comment]
具体什么支持呢？已经有一个multihead-attn的算子了。

**Comment by feifeibear** [comment]
unitest问题已经解决了，这个issue先close了。
