### ISSUE TITLE
关于GPU安装的第一步

### ISSUE THREAD

**Issue by ShenYounger** [Tencent/TurboTransformers#26]
sh tools/build_docker_gpu.sh $PWD

我的系统是CentOS Linux release 7.6.1810 (Core) 
cuda版本是10.2
cudnn版本是7.65
显卡是K80，驱动型号是440.33.01
pytorch版本是1.5.0
python版本是3.7.5
----------------------------------------------

请问build_docker_gpu.sh该怎么修改？

我目前改成

CUDA_VERSION=10.2
DOCKER_BASE=${CUDA_VERSION}-cudnn7-devel-CentOS7.6
PYTORCH_VERSION=1.5.0

结果报错

++ cat ../CMakeLists.txt
++ grep TURBO_TRANSFORMERS_VERSION
++ sed 's#set(TURBO_TRANSFORMERS_VERSION ##g'
++ sed 's#)##g'
+ VERSION=0.2.0
+ CUDA_VERSION=10.2
+ DOCKER_BASE=10.2-cudnn7-devel-CentOS7.6
+ PYTORCH_VERSION=1.5.0
+ sed s#IMAGE_BASE#nvidia/cuda:10.2-cudnn7-devel-CentOS7.6#g ./docker/Dockerfile_dev.gpu
+ sed s#CUDA_VERSION#10.2#g
+ sed s#PYTORCH_VERSION#1.5.0#g
+ docker build -t ccr.ccs.tencentyun.com/mmspr/turbo_transformers:0.2.0-cuda10.2-cudnn7-devel-CentOS7.6-gpu-dev -f Dockerfile.gpu .
Sending build context to Docker daemon  34.82kB
Step 1/6 : FROM nvidia/cuda:10.2-cudnn7-devel-CentOS7.6
manifest for nvidia/cuda:10.2-cudnn7-devel-CentOS7.6 not found

**Comment by feifeibear** [comment]
FROM后面的docker镜像必须是合法的
nvidia/cuda:10.2-cudnn7-devel-CentOS7.6 
这个不合法，nvidia没有提供这个名字的镜像

**Comment by ShenYounger** [comment]
> FROM后面的docker镜像必须是合法的
> nvidia/cuda:10.2-cudnn7-devel-CentOS7.6
> 这个不合法，nvidia没有提供这个名字的镜像

我现在改成了nvidia/cuda:10.2-cudnn7-devel-centos7，好像是可以了。

**Comment by ShenYounger** [comment]
> FROM后面的docker镜像必须是合法的
> nvidia/cuda:10.2-cudnn7-devel-CentOS7.6
> 这个不合法，nvidia没有提供这个名字的镜像

不过报了另外一个错误。

++ cat ../CMakeLists.txt
++ grep TURBO_TRANSFORMERS_VERSION
++ sed 's#set(TURBO_TRANSFORMERS_VERSION ##g'
++ sed 's#)##g'
+ VERSION=0.2.0
+ CUDA_VERSION=10.2
+ DOCKER_BASE=10.2-cudnn7-devel-centos7
+ PYTORCH_VERSION=1.5.0
+ sed s#IMAGE_BASE#nvidia/cuda:10.2-cudnn7-devel-centos7#g ./docker/Dockerfile_dev.gpu
+ sed s#CUDA_VERSION#10.2#g
+ sed s#PYTORCH_VERSION#1.5.0#g
+ docker build -t ccr.ccs.tencentyun.com/mmspr/turbo_transformers:0.2.0-cuda10.2-cudnn7-devel-centos7-gpu-dev -f Dockerfile.gpu .
Sending build context to Docker daemon  34.82kB
Step 1/6 : FROM nvidia/cuda:10.2-cudnn7-devel-centos7
10.2-cudnn7-devel-centos7: Pulling from nvidia/cuda
ab5ef0e58194: Pull complete 
c9fcd75aa85e: Pull complete 
8ff47b5afaab: Pull complete 
66d90780bff5: Pull complete 
42d4038c8406: Pull complete 
dc73c0f38d0f: Pull complete 
f54d3da29cc8: Pull complete 
b6a626c69094: Pull complete 
Digest: sha256:b8631d58b1123f484fca3fcbc22dd88b0dfb1e8676bdd2a871e060bce40ff264
Status: Downloaded newer image for nvidia/cuda:10.2-cudnn7-devel-centos7
 ---> 664069eeb4da
Step 2/6 : RUN apt-get update &&     apt-get install -y curl git wget bzip2 build-essential ninja-build g++ && rm -rf /var/lib/apt/lists/*
 ---> Running in 2deda62ab1eb
OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/2deda62ab1ebd989d50b0c56e5b0c3753e34777b787974ea3a0801128ad5d3e7/log.json: no such file or directory): exec: "nvidia-container-runtime": executable file not found in $PATH: unknown

**Comment by ShenYounger** [comment]
我注意到上面是apt-get update执行的命令，但是我的系统是centos啊。

**Comment by feifeibear** [comment]
是的，需要定制自己的dockerfile。如果成功可以欢迎交一个PR

**Comment by ShenYounger** [comment]
> 是的，需要定制自己的dockerfile。如果成功可以欢迎交一个PR

但是我现在被卡在这里了。我现在该怎么办啊？我想在centos系统上跑我们的这个框架

**Comment by feifeibear** [comment]
issue发起人成功修改了dockerfile，安装了centos版本的turbo
