### ISSUE TITLE
有本地gpu安装说明么？

### ISSUE THREAD

**Issue by jeshxxx** [Tencent/TurboTransformers#38]
如题

**Comment by feifeibear** [comment]
没有，步骤和docker内操作一致，你可以自己试试，本地操作因为环境问题我们没法保证你装成功
我做了gpu编译好的docker image，你可以直接用
docker pull thufeifeibear/turbo_transformers:0.2.0-cuda10.0-cudnn7-devel-ubuntu18.04-gpu-release

**Comment by jeshxxx** [comment]
> docker pull thufeifeibear/turbo_transformers:0.2.0-cuda10.0-cudnn7-devel-ubuntu18.04-gpu-release

好的，编译成功了
