### ISSUE TITLE
无法确定turbo_transformers.BertModel.from_torch到底调用的是哪个函数

### ISSUE THREAD

**Issue by ShenYounger** [Tencent/TurboTransformers#39]
情况是这样的。在运行gpu_benchmark.py时候，我看到在运行turbo_transformers时，调用的函数是turbo_transformers.BertModel.from_torch。

我看了一下代码，觉得调用的函数应该是TurboTransformers/turbo_transformers/python/turbo_transformers/layers/modeling_bert.py中class BertModel中的from_torch函数。于是我在此函数中，加载了一些print以打印信息。却发现执行bash run_gpu_benchmark.sh这些print打印不出任何信息。

所以我很疑问turbo_transformers.BertModel.from_torch到底调用的是哪个函数？

**Comment by feifeibear** [comment]
就是你看到的位置，你打印不出信息是因为你没更新pip
pip uninstall turbo_transformers
再重新安装一遍

**Comment by ShenYounger** [comment]
> 就是你看到的位置，你打印不出信息是因为你没更新pip
> pip uninstall turbo_transformers
> 再重新安装一遍

我现在已经执行了pip uninstall turbo_transformers，
不知道“再重新安装一遍”在这里是什么意思？

**Comment by feifeibear** [comment]
参考readme
2. Install pip package in docker and single test
cd /workspace
sh tools/build_and_run_unittests.sh $PWD -DWITH_GPU=ON
或者
找到你新编译出来的*whl进行pip install

**Comment by ShenYounger** [comment]
> 参考readme
> 2. Install pip package in docker and single test
> cd /workspace
> sh tools/build_and_run_unittests.sh $PWD -DWITH_GPU=ON
> 或者
> 找到你新编译出来的*whl进行pip install

已经解决，谢谢
