### ISSUE TITLE
怎么设置core::IsCompiledWithCUDA()为true

### ISSUE THREAD

**Issue by ShenYounger** [Tencent/TurboTransformers#41]
我现在在使用C++ APIs。我按照https://github.com/Tencent/TurboTransformers/blob/master/example/cpp/README.md里面的说明，进行./bert_model_example bert.npz。

但是我发现example/cpp/bert_model_example.cpp里面的代码core::IsCompiledWithCUDA()永远返回false，导致没办法在c++ api中使用GPU。

我在代码库中grep了这个函数，返回如下：

example/cpp/bert_model_test.cpp:97:  if (core::IsCompiledWithCUDA()) {
example/cpp/bert_model_test.cpp:106:  if (core::IsCompiledWithCUDA()) {
example/cpp/bert_model_example.cpp:140:  if (core::IsCompiledWithCUDA()) {
example/cpp/bert_model_example.cpp:149://  if (core::IsCompiledWithCUDA()) {
turbo_transformers/core/config.h:26:constexpr bool IsCompiledWithCUDA() {
turbo_transformers/python/pybind.cpp:52:  m.def("is_compiled_with_cuda", &core::IsCompiledWithCUDA)

**Comment by feifeibear** [comment]
constexpr bool IsCompiledWithCUDA() {
#ifdef TT_WITH_CUDA
  return true;
#else
  return false;
#endif
}
这是编译时候决定的请加 -DWITH_GPU=ON

**Comment by ShenYounger** [comment]
> constexpr bool IsCompiledWithCUDA() {
> #ifdef TT_WITH_CUDA
> return true;
> #else
> return false;
> #endif
> }
> 这是编译时候决定的请加 -DWITH_GPU=ON

编译时候加 -DWITH_GPU=ON，指的是readme第二步
sh tools/build_and_run_unittests.sh $PWD -DWITH_GPU=ON？


如果指的是这点的话，我确信我在第二步已经加上了-DWITH_GPU=ON
