### ISSUE TITLE
在显卡K80上跑的benchmark，Turbo相对pytorch加速不如预期

### ISSUE THREAD

**Issue by ShenYounger** [Tencent/TurboTransformers#42]
我cd benchmark，然后执行脚本bash run_gpu_benchmark.sh，结果如下：

{"QPS": 141.9624342537054, "elapsed": 1.0566175537109375, "n": 150, "batch_size": 1, "seq_len": 10, "framework": "turbo", "thread_num": 1}
{"QPS": 79.07311483207774, "elapsed": 1.896978515625, "n": 150, "batch_size": 1, "seq_len": 10, "framework": "torch", "thread_num": 1}
{"QPS": 95.6774176067004, "elapsed": 1.56776806640625, "n": 150, "batch_size": 1, "seq_len": 20, "framework": "turbo", "thread_num": 1}
{"QPS": 78.33956337296448, "elapsed": 1.9147413330078125, "n": 150, "batch_size": 1, "seq_len": 20, "framework": "torch", "thread_num": 1}
{"QPS": 95.04851976317696, "elapsed": 1.578141357421875, "n": 150, "batch_size": 1, "seq_len": 30, "framework": "turbo", "thread_num": 1}
{"QPS": 78.68219615532972, "elapsed": 1.9064033203125, "n": 150, "batch_size": 1, "seq_len": 30, "framework": "torch", "thread_num": 1}

以上是batch size为1，seq_len分别为10、20、30时，turbo相对于torch的QPS。

在Readme中GPU M40测试中，seq_len分别为10、20、30时，turbo相对torch加速倍数分别为3.31、3.17、2.88。而换成了K80显卡，turbo相对torch加速倍数分别为1.79、1.22和1.20。

我的问题是为什么换成了显卡K80，turbo相对torch的加速倍数就不是那么明显了呢，turbo是不是针对具体的显卡型号进行了优化？

**Comment by feifeibear** [comment]
没有针对硬件优化，但是对Tensor Core做了支持。K80比M40还老，我都拿不到这种硬件了。
M，K, P, V开头代表不同代际的显卡，体系架构也差别很大，加速在老卡上不明显也很有可能。其实，没准矩阵转个置性能就提升了也是有可能的。
