### ISSUE TITLE
benchmark程序运行失败

### ISSUE THREAD

**Issue by zhoushan2186new** [Tencent/TurboTransformers#45]
我们试图重现性能，按照文档自己编译成功docker镜像，并且单元测试成功，但是运行benchmark时模型加载不了，请问是什么原因？报错如下：
   model = transformers.BertModel.from_pretrained(model_id)
  File "/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py", line 629, in from_pretrained
    "Unable to load weights from pytorch checkpoint file. "
我们使用的bert模型下载路径是https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-config.json  bert-base-uncased-vocab.txt以及bert-base-uncased-pytorch_model.bin
对模型文件有什么特殊要求吗？或者需要做什么预处理？
谢谢

**Comment by zhoushan2186new** [comment]
已解决，忘记安装whl文件

**Comment by feifeibear** [comment]
Generally, a PyTorch saved model contains the following files.

added_tokens.json
config.json
pytorch_model.bin
special_tokens_map.json
tokenizer_config.json
vocab.txt

make sure these files are included in your local directory.
