### ISSUE TITLE
wccms / LAB_seq-malGAN 请教，很心急

### ISSUE THREAD

**Issue by Joey-la** [Tencent/TurboTransformers#50]
你好，很抱歉在这个项目里提别的问题，实在没有别的方式联系您了。我在研究您在这个LAB_seq-malGAN中提交的代码，比较熟悉pytorch，但是好像您没有写完，我就去攻了下tensorflow版的，但是不是很明白，不知道为什么运行起来很慢，您里面的候选API词典有100多个，我用了几万的一个，就，运行贼慢。很想问下您有没有这个的原论文我想研究下，然后如果您pytorch的有更新了，也非常希望您能提交下，真的非常感谢

**Comment by feifeibear** [comment]
这个项目的contributor没有参与这个wccms / LAB_seq-malGAN项目
