### ISSUE TITLE
关于自己直接用bert tensorflow 训练的finetune 模型的使用方法

### ISSUE THREAD

**Issue by 652994331** [Tencent/TurboTransformers#52]
您好，问一下这个自己用tensorflow bert fintune（带自己的任务)的 模型 想按(example/python）中提供的方式要怎么用呢，现在看起来似乎只能 转huggenface 自带的预训练模型

**Comment by feifeibear** [comment]
训练端你可以用tensorflow方式正常finetune，把参数存成文件。
turbo提供了tensorflow和pytorch的模型载入方法，虽然目前提供的例子是针对huggingface的，但是，稍作更改也可以支持其他存储方式，只是参数名字改成你对应的即可。
参考一下issue #13

**Comment by 652994331** [comment]
好的 收到，BTW 我试了一下 现在默认的 tensorflow 模型转化的方式，出现了如下问题
![image](https://user-images.githubusercontent.com/51428350/82425545-3cecca80-9ab9-11ea-8b81-512902e0c10b.png)


我看了一下，似乎问题是TensorFlow不是 TensorFlow2.0导致的？请问下这个thufeifeibear/turbo_transformers:0.2.0-cuda10.0-cudnn7-devel-ubuntu18.04-gpu-release中的tensorflow 版本是？ 谢谢

**Comment by feifeibear** [comment]
tensorflow 2.0
网上有很多方法把模型从tf 1.0转换到tf 2.0
也欢迎你贡献一个直接从tensorflow 1.0转换到npz的脚本。

**Comment by 652994331** [comment]
好的 谢谢您

**Comment by feifeibear** [comment]
我知道你的问题了，请在docker container里执行如下命令安装tensorflow 2.0
pip install tensorflow-gpu

**Comment by 652994331** [comment]
问题已解决，谢谢
