### ISSUE TITLE
找不到 turbo_transformer.BertModel 

### ISSUE THREAD

**Issue by 652994331** [Tencent/TurboTransformers#53]
docker 环境中跑 run_gpu_benchmarrk.py  以及 example/python 中 gpu_example 的时候都存在这个问题 AttributeError: module 'turbo_transformers' has no attribute 'BertModel' 麻烦请教一下 谢谢

**Comment by feifeibear** [comment]
大概率是你没装wheel包成功。试一下安装好的镜像吧
docker pull thufeifeibear/turbo_transformers:0.2.0-cuda10.0-cudnn7-devel-ubuntu18.04-gpu-release

**Comment by 652994331** [comment]
谢谢 您的回复解决了问题.
