### ISSUE TITLE
关于gpu_example结果的问题

### ISSUE THREAD

**Issue by 652994331** [Tencent/TurboTransformers#54]
安装GPU 镜像后， 在docker 中运行gpu_example.py 的过程中，出现了如下问题
![image](https://user-images.githubusercontent.com/51428350/82414195-4110ec00-9aa9-11ea-83a2-2f5ac15f8d83.png)
目前已通过修改 代码中该部分为如下图 解决
![image](https://user-images.githubusercontent.com/51428350/82414291-67cf2280-9aa9-11ea-9319-22fdfa295c9c.png)
首先想问问这种改法是否正确

第二是跑出来的结果是
![image](https://user-images.githubusercontent.com/51428350/82414405-9816c100-9aa9-11ea-9258-a06af1e34321.png)
对这个0.42的意义不是很清楚， 想请教一下。
非常感谢

**Comment by feifeibear** [comment]
This a bug. I am going to fix it. The value is the max diff between torch and turbo.

**Comment by 652994331** [comment]
谢谢您。请问这个diff 指的是CPU预测的速度吗，比如说我想测试一下TURBO GPU的预测一条样本的速度这个要怎么解决呢

**Comment by feifeibear** [comment]
这个就是一个example，diff是数值上的差距
速度可以在benchmark目录下测试

**Comment by 652994331** [comment]
就是说 在benchmark 目录下 自己去开发一个脚本来测速对吧

**Comment by feifeibear** [comment]
benchmark已有的脚本就可以测，或者你自己写benchmark的方法都可以
