### ISSUE TITLE
基于python还是基于c++搭建服务？

### ISSUE THREAD

**Issue by ShenYounger** [Tencent/TurboTransformers#59]
我目前的需求，是远程传过来一个文本，我需要在机器上搭建一个服务器，这个服务器用bert返回CLS向量(也就是原始bert中的pooled_output)，那么我是基于example中的cpp接口进行搭建服务器，还是基于python接口搭建服务器，这两者在速度上，有什么差异么？

**Comment by feifeibear** [comment]
没区别，C++比较难，python的asyncio很好写

**Comment by ShenYounger** [comment]
> asyncio

没有区别？是因为python只是一个接口，底层调用的依然是c++应用程序是么？

另外项目主页Chinese Version README中提到的"在工蜂上我们还内部开源了一套可以使用turbo的python severing框架bertserving供使用者参考，它通过asyncio方式异步响应BERT推理的http请求"

这个框架是https://github.com/hanxiao/bert-as-service么？如果不是，是指的哪个框架呢？因为我点击“https://git.code.oa.com/PRC_alg/bert-serving/tree/develop” 这个url，好像是没有权限进去，不知道怎么可以进去这个项目。

**Comment by feifeibear** [comment]
这个repo是Tencent内部python项目，没有公开，就是用asyncio实现的。
另外我们在开发一套基于gRPC的C++ serving框架，感兴趣可以加入我们哦。
