### ISSUE TITLE
没看见dropout

### ISSUE THREAD

**Issue by lsy641** [Tencent/TurboTransformers#61]
bert_attention.cpp 里面，dense和laynorm之间应该要有dropout吧，我似乎没看到？
![image](https://user-images.githubusercontent.com/26696711/82548205-8a3a6c00-9b8d-11ea-9a58-efd838f012f2.png)

**Comment by ShenYounger** [comment]
> bert_attention.cpp 里面，dense和laynorm之间应该要有dropout吧，我似乎没看到？
> ![image](https://user-images.githubusercontent.com/26696711/82548205-8a3a6c00-9b8d-11ea-9a58-efd838f012f2.png)

是不是因为这不是一个训练框架，而只是一个加快推理的框架，所以dropout都弄掉了？

**Comment by lsy641** [comment]
> > bert_attention.cpp 里面，dense和laynorm之间应该要有dropout吧，我似乎没看到？
> > ![image](https://user-images.githubusercontent.com/26696711/82548205-8a3a6c00-9b8d-11ea-9a58-efd838f012f2.png)
> 
> 是不是因为这不是一个训练框架，而只是一个加快推理的框架，所以dropout都弄掉了？

哦哦，对的，应该是这个原因

**Comment by feifeibear** [comment]
ShenYounger is right. Inference shall not have dropout.
