### ISSUE TITLE
大batchsize的效果

### ISSUE THREAD

**Issue by jeshxxx** [Tencent/TurboTransformers#75]
我用python的api测试的，batchsize=1的时候是几毫秒，batchsize=120的时候就快100ms了，到batchsize=256时就到100多毫秒了，这个符合预期么？

**Comment by feifeibear** [comment]
CPU的话，符合预期。大 batch情况下，耗时基本就是矩阵乘法，Pytorch和Turbo都用的MKL，没啥区别。

**Comment by jeshxxx** [comment]
> CPU的话，符合预期。大 batch情况下，耗时基本就是矩阵乘法，Pytorch和Turbo都用的MKL，没啥区别。

GPU

**Comment by feifeibear** [comment]
序列长度多少？

**Comment by jeshxxx** [comment]
50，有对大的batchsize做过测试么？

**Comment by feifeibear** [comment]
"batch_size": 120, "seq_len": 50， Turbo性能是pytorch的2.14x，这不香么？
{"QPS": 9.329495930250356, "elapsed": 16.0780390625, "n": 150, "batch_size": 120, "seq_len": 50, "framework": "turbo", "thread_num": 1}
{"QPS": 4.353913283653369, "elapsed": 34.451765625, "n": 150, "batch_size": 120, "seq_len": 50, "framework": "torch", "thread_num": 1}

**Comment by jeshxxx** [comment]
你这是怎么测的？方便测试么？实际我们用tensorRT做到batchsize=256，seq_len=50，15ms左右，想做到10ms以内

**Comment by feifeibear** [comment]
在benchmark目录有测试脚本
/myspace/benchmark# `bash run_gpu_benchmark.sh`
GeForce RTX 2060上已经接近10ms了 1000ms/QPS是单次推理延迟。

**Comment by jeshxxx** [comment]
好的，我试一下
