### ISSUE TITLE
gpu benchmark does not support PyTorch 1.5.0.

### ISSUE THREAD

**Issue by smartcat2010** [Tencent/TurboTransformers#77]
您好，我试图用最新的pytorch做gpu benchmark的对照组，配置如下：
pytorch: 1.5.0
torchvision: 0.6.0
CUDA: 10.2
OS: Ubuntu18.04
即Dockerfile.gpu里对应行修改为"conda install pytorch=1.5.0 torchvision=0.6.0 cudatoolkit=10.2 -c pytorch"

在docker里build后在test时，有好几个测试用例通不过：

> Test project /tmp/build
      Start  1: tt_core_test
 1/12 Test  #1: tt_core_test .....................   Passed    0.52 sec
      Start  2: tt_kernels_test
 2/12 Test  #2: tt_kernels_test ..................   Passed   29.18 sec
      Start  3: bert_attention_test
 3/12 Test  #3: bert_attention_test ..............***Failed    4.50 sec
date       time         ( uptime  ) [ thread name/id ]                   file:line     v|
2020-06-08 13:10:51.358 (   0.000s) [main thread     ]             loguru.cpp:610   INFO| arguments: turbo_transformers_cxx
2020-06-08 13:10:51.358 (   0.000s) [main thread     ]             loguru.cpp:613   INFO| Current dir: /tmp/build/turbo_transformers/python
2020-06-08 13:10:51.358 (   0.000s) [main thread     ]             loguru.cpp:615   INFO| stderr verbosity: 0
2020-06-08 13:10:51.358 (   0.000s) [main thread     ]             loguru.cpp:616   INFO| -----------------------------------
FFFFFFFFFFFFFFFFFFFFFFFBertAttention "(1,010)"  CPU Torch QPS, 492.80298203436234, time, 0.002029208500061941
BertAttention "(1,010)"   CPU Turbo QPS, 1082.363535550833, time, 0.0009239040000466048`

...

> The following tests FAILED:
          3 - bert_attention_test (Failed)
          5 - bert_encoder_test (Failed)
          6 - bert_intermediate_test (Failed)
          7 - bert_layer_test (Failed)
          8 - bert_model_test (Failed)
          9 - bert_output_test (Failed)
         10 - bert_pooler_test (Failed)

请问目前这个gpu benchmark对pytorch版本最高支持到多少呢？[官方首页](https://github.com/Tencent/TurboTransformers)里的benchmark实验结果，是和哪个版本的pytorch比较的呢？

**Comment by feifeibear** [comment]
现在比较的是1.4.0。已知Pytorch 1.5.0对tensor transpose，concat的操作和1.4.0结果不一致，这是Pytorch bug还是feature有待考证。
你可以测一下1.4.0和1.5.0性能有啥区别，应该没有区别。

**Comment by smartcat2010** [comment]
> 现在比较的是1.4.0。已知Pytorch 1.5.0对tensor transpose，concat的操作和1.4.0结果不一致，这是Pytorch bug还是feature有待考证。
> 你可以测一下1.4.0和1.5.0性能有啥区别，应该没有区别。

谢谢！测了一下，pytorch1.4.0和1.5.0在该GPU benchmark上确实没有什么性能差别。

**Comment by feifeibear** [comment]
The member function `from_torch` of class `BertModelWithPooler` and `BertModel` does not support **PyTorch version as 1.5.0**. In my opinion, the tensor transpose API of PyTorch is not stable. We use the following way to transpose weight matrices.

weight = torch.clone(torch.t(pooler_params['dense.weight']))

I have no idea, why it does not work as predicted in Pytorch 1.5.0.

**Comment by feifeibear** [comment]
The bug will fix in version v0.3.0

**Comment by feifeibear** [comment]
The bug fixed!

**Comment by smartcat2010** [comment]
Great work!
