### ISSUE TITLE
这东西只支持Bert吗？Resnet能支持吗？

### ISSUE THREAD

**Issue by rexxar-liang** [Tencent/TurboTransformers#78]

**Comment by feifeibear** [comment]
ResNet有大量已有工作可以直接使用，并不在本项目研究范围内。
这个runtime只针对Transformer结构的NLP模型，这类模型之所以值得研究在于。
1. 目前已有Transformer计算优化比较差。
2. NLP输入是变长序列，内存管理和serving方式没有很好解决方案。
