### ISSUE TITLE
docker run GPU容器失败

### ISSUE THREAD

**Issue by smartcat2010** [Tencent/TurboTransformers#81]
不好意思，再请问个问题。运行完"sh tools/build_docker_gpu.sh $PWD"后，再运行下面这条docker run实例化刚创建的image，会报错。（git clone后没有对build_docker_gpu.sh等进行过改动)
sudo docker run --gpus all --net=host --rm -it -v $PWD:/workspace -v /etc/passwd:/etc/passwd --name=gt_gpu_env ccr.ccs.tencentyun.com/mmspr/turbo_transformers:0.2.1-cuda10.0-cudnn7-devel-ubuntu18.04-gpu-dev

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:432: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.

此问题从今天中午开始出现的。会不会是刚刚从0.2.0升级到0.2.1造成的问题呢？

**Comment by feifeibear** [comment]
升级完你的镜像名字的版本号不应该是0.2.1么？

**Comment by smartcat2010** [comment]
抱歉，刚才复制粘贴错了。。。是的，是0.2.1：
![image](https://user-images.githubusercontent.com/10429114/84364980-6655cd80-ac03-11ea-9018-f92f169bae1f.png)

**Comment by feifeibear** [comment]
你可以回推到0.2.0再试试，看有这个问题么
git reset --hard 4750f34df28369a69402fd1432db30087436fbe6

**Comment by smartcat2010** [comment]
> 你可以回推到0.2.0再试试，看有这个问题么
> git reset --hard [4750f34](https://github.com/Tencent/TurboTransformers/commit/4750f34df28369a69402fd1432db30087436fbe6)

谢谢！回退了，还是同样的报错，看来不是版本更新造成的问题。
![image](https://user-images.githubusercontent.com/10429114/84367258-8d61ce80-ac06-11ea-8231-1cc74061fb9b.png)

**Comment by smartcat2010** [comment]
找到原因了。是因为一上来没有安装NVIDIA显卡Driver。需要用dpkg和apt-get install cuda-drivers来安装Driver。
