### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by hadoop2xu** [Tencent/TurboTransformers#83]
请问有turbo 优化原理的paper吗？

**Comment by feifeibear** [comment]
还有其他人也问了同样的问题，work in progress，我尽快写一个technique report吧。

**Comment by hadoop2xu** [comment]
> 还有其他人也问了同样的问题，work in progress，我尽快写一个technique report吧。

谢谢大佬，目前正在啃源码

**Comment by feifeibear** [comment]
Related Paper about technical details will be released in Mid of August, 2020.

**Comment by feifeibear** [comment]
We have added an arXiv paper with regard to the implementation details of this runtime.

**Comment by hadoop2xu** [comment]
> We have added an arXiv paper with regard to the implementation details of this runtime.

could you give  a link please ?

**Comment by hadoop2xu** [comment]
> We have added an arXiv paper with regard to the implementation details of this runtime.

thinks
