### ISSUE TITLE
bert的输出为什么没有把hidden作为输出？

### ISSUE THREAD

**Issue by shizhh** [Tencent/TurboTransformers#9]
https://github.com/Tencent/TurboTransformers/blob/7137d75efae14428e8265bf95d12daff8001f213/turbo_transformers/python/turbo_transformers/layers/modeling_bert.py#L376-L385

基于工作需求，要对hidden做进一步的处理

**Comment by chengduoZH** [comment]
这里只返回了seq_pool之后的结果，确实跟huggingface/transformers里面的返回结果不一样，我们内部讨论一下是否要做出一致的，稍后答复。

一个临时的解决方案是您那边将hidden_cache放到返回值列表中（这里的hidden_cache是encoder的最后一层的state，维度为[batch, seq_len, hidden_size]）：
```
 hidden_cache = self.encoder(hidden_states=hidden_cache, 
                             attention_mask=extended_attention_masks, 
                             return_type=ReturnType.turbo_transformers, 
                             output=hidden_cache) 
  
 self.seq_pool = SequencePool(PoolingMap[pooling_type]) 
 output = self.seq_pool(input_tensor=hidden_cache, 
                        return_type=return_type, 
                        output_tensor=output) 
 return  convert_returns_as_type(hidden_cache, return_type), output 
```

**Comment by shizhh** [comment]
@chengduoZH 赞！测试了下，在我的机器上，cpu环境下速度提升了4倍。另外问一下，会不会提供GPU的版本？

**Comment by feifeibear** [comment]
> @chengduoZH 赞！测试了下，在我的机器上，cpu环境下速度提升了4倍。另外问一下，会不会提供GPU的版本？

已经有GPU版本了呀，另外你要要hidden_state就给加一下也不麻烦

**Comment by shizhh** [comment]
> cpu环境下速度提升了4倍

更正下，是因为线程数设置了4

**Comment by shizhh** [comment]
> 已经有GPU版本了呀，另外你要要hidden_state就给加一下也不麻烦

@feifeibear 什么时候提供conda的安装方式呢

**Comment by feifeibear** [comment]
> > 已经有GPU版本了呀，另外你要要hidden_state就给加一下也不麻烦
> 
> @feifeibear 什么时候提供conda的安装方式呢

已经加了你的hidden_state返回需求到master，什么情况下必须一个conda包进行部署？gpu的wheel包满足不了需求么？

**Comment by reyoung** [comment]
Hidden需求已经满足了。

使用 #19 这个issue来跟踪conda 安装包的开发进度。
