### ISSUE TITLE
benchmark的baseline用fp16还是fp32做对比更合理呢？

### ISSUE THREAD

**Issue by smartcat2010** [Tencent/TurboTransformers#93]
请问，TurboTransformer对绝大部分网络层计算，使用的是16位Float还是32位Float的呢？[这个issue](https://github.com/Tencent/TurboTransformers/issues/42)里，您有说"对Tensor Core做了支持"，不知道有没有大量转成fp16去计算。
我用[onnxruntime针对transformer的优化工具](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers)做baseline时(官方README说该工具使用了最新的优化技术，比onnxruntime-gpu还要快: "Some of the latest optimizations that have not yet been integrated into ONNX Runtime are available in this tool that tunes models for the best performance.")，不太清楚其fp32还是fp16版本，哪个来和TurboTransformer比较更公平。
我在V100卡上的测试结果，是Turbo相比fp32的onnxruntime-transformers-tools达到1.5X至2.5X的加速比，相比fp16的onnxruntime-transformers-tools会落败即加速比0.7X至0.8X

**Comment by feifeibear** [comment]
turbo只支持FP32，所以比较用fp32才是公平的。用tensor-core输入输出矩阵也是FP32的。

**Comment by smartcat2010** [comment]
> turbo只支持FP32，所以比较用fp32才是公平的。用tensor-core输入输出矩阵也是FP32的。

谢谢！都用FP32来比，那Turbo的加速比的确很高。我是微软产品组的，希望能借鉴融合Turbo的技术来进一步提升onnxruntime的infer速度。期待实现原理的公布~

**Comment by smartcat2010** [comment]
> turbo只支持FP32，所以比较用fp32才是公平的。用tensor-core输入输出矩阵也是FP32的。

谢谢！都用FP32来比，那Turbo的加速比的确很高。期待实现原理的公布~
